CREATE TABLE [dbo].[Modules]
(
	[MacAddress] NVARCHAR(20) NOT NULL PRIMARY KEY,
	[IssueDate] NVARCHAR(20) NOT NULL,
	[ID] NVARCHAR(12) NOT NULL,
	CONSTRAINT [FK_ID] FOREIGN KEY (ID) REFERENCES Students(ID)
)